apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-backend
  namespace: cars-backend
  labels:
    app.kubernetes.io/instance: cars-backend
    app.kubernetes.io/name: cars-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cars-backend
      app.kubernetes.io/name: cars-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cars-backend
        app.kubernetes.io/name: cars-backend
    spec:
      containers:
        - name: cars-backend
          image: silverfoxjv/cars-backend:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/cars
            - name: SPRING_DATASOURCE_USERNAME
              value: cars_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: cars_password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver

          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

