apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-backend
  namespace: cars-backend
  labels:
    app.kubernetes.io/instance: cars-backend
    app.kubernetes.io/name: cars-backend
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: cars-backend
      app.kubernetes.io/name: cars-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cars-backend
        app.kubernetes.io/name: cars-backend
    spec:
      containers:
        - name: cars-backend
          image: silverfoxjv/cars-backend:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://cars-mysql-db-instances.cars-mysql.svc.cluster.local:3306/cars
            - name: SPRING_FLYWAY_URL
              value: jdbc:mysql://cars-mysql-db-instances.cars-mysql.svc.cluster.local:3306/cars
            - name: SPRING_DATASOURCE_USERNAME
              value: cars_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: cars_password
            - name: SPRING_FLYWAY_USER
              value: cars_user
            - name: SPRING_FLYWAY_PASSWORD
              value: cars_password
            - name: CORS_ALLOWED_ORIGINS
              value: "https://cars-frontend-external.at-dias.cloud,https://cars-frontend.at-dias.cloud"
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

